environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: i686-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: beta
    - TARGET: i686-pc-windows-msvc
      TOOLCHAIN: beta
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: nightly
    - TARGET: i686-pc-windows-msvc
      TOOLCHAIN: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - choco install make -y
  - rustc -Vv
  - cargo -V
  - make -v

build_script:
  - git submodule -q update --init

test_script:
  - SET RUST_BACKTRACE=1
  - cargo test --target %TARGET% --all --verbose
  - cargo test --release --target %TARGET% --all --verbose
  - if [%TOOLCHAIN%]==[nightly] (
      cargo bench --target %TARGET% --all --verbose
    )
cache:
  - C:\Users\appveyor\.cargo\registry
  - target
